feat: Add callback function to notifications
m4xshen/hardtime.nvim pull request #101
Opened 2024-06-11 20:41 UTC by tris203

This commit introduces a new `callback` function to the notification system. This function can be used to trigger custom events on a notification. It receives a config object and the notification text as parameters. The `callback` function is optional and is added to the `config` object in `config.lua`. The `notify` function in `util.lua` has been updated to call the `callback` function if it is provided.

This would be one way to handle a request we had in https://github.com/tris203/precognition.nvim/issues/62

But open to your ideas about implementation.

Draft as this is just a talking point for now

2024-06-11 21:04 UTC, tris203 commented
I am open to the implementation, perhaps it should overwrite the notify function completely rather than just be additional.

It depends what you would like to consider

2024-08-12 12:34 UTC, tris203 commented
@m4xshen did you have any thoughts on this?

2024-08-18 11:25 UTC, m4xshen commented
Hi @tris203, sorry for the late reply.

> I am completely open to the implementation, perhaps it should overwrite the notify function completely rather than just be additional.

Could you please provide an example of how precognition.nvim will use this option to achieve integration under both implementation?

It's hard to say which one is better. It would be nice to have some example code.

2024-08-18 11:37 UTC, tris203 commented
> It's hard to say which one is better. It would be nice to have some example code.
In the current implementation you can pass something like this in setup:
```lua
  {
    'm4xshen/hardtime.nvim',
    opts = {
      callback = function(config, text)
        require('precognition').peek()
      end,
    },
  },
```

This will toggle the precognition hints every time that you get a notification from hardtime.

If we were to overwrite the function entirely, then it would be very similar, except that you would also be required to recreate the notification as well as the additional actions

2024-08-18 12:21 UTC, m4xshen commented
Got it. I prefer to overwrite the function entirely and the default value of `callback` should be `util.notify`.

2024-08-18 13:19 UTC, tris203 commented
Have made changes and rebased @m4xshen

2024-08-18 14:24 UTC, m4xshen requested changes

2024-08-18 14:24 UTC, m4xshen commented on lua/hardtime/config.lua
> +   callback = nil,
What I mean [in this comment](https://github.com/m4xshen/hardtime.nvim/pull/101#issuecomment-2295242575) is that we can do this:

```lua
local util = require("hardtime.util")

-- ...

   ---@type function
   callback = util.notify,
}
```

And then just replace the `util.notify` inside `init.lua` with `config.callback`.

2024-08-18 14:58 UTC, m4xshen commented on lua/hardtime/config.lua
> +   callback = nil,
How about extracting that logic out of `notify`? Like this:


```lua
function M.callback_wrapper(text) -- or other better name
   if text ~= last_notification_text then
      config.callback() -- default is M.notify
   end
   last_notification_text = text
   last_notification_time = M.get_time()
end

function M.notify(text)
   logger.info(text)
   vim.notify(text, vim.log.levels.WARN, { title = "hardtime" })
end
```

and the `callback_wrapper` will be called in `init.lua`.

2024-08-19 10:49 UTC, merged

2024-08-19 10:55 UTC, m4xshen commented
@tris203 Thanks for the PR! You can now use this option to integrate with precognition.nvim!

btw I'm looking forward to the inlay hint feature, is this available now?

2024-08-19 11:31 UTC, tris203 commented
> @tris203 Thanks for the PR! You can now use this option to integrate with precognition.nvim!
> 
> btw I'm looking forward to the inlay hint feature, is this available now?

Thanks @m4xshen 
Yeah inlay hints are merged as of a few weeks ago!