feat: force exit insert mode if user is inactive
m4xshen/hardtime.nvim pull request #114
Opened 2024-10-02 12:13 UTC by csessh

#111 

I added two configuration options: `force_exit_insert_mode` and `max_insert_idle_ms` to enable to this feature. Default = false. 

```
return {
    dir = "~/Documents/nvim-plugins/hardtime.nvim",
    dev = true,
    dependencies = { "MunifTanjim/nui.nvim", "nvim-lua/plenary.nvim" },
    opts = {
        force_exit_insert_mode = true,
        max_insert_idle_ms = 3000,
    },
}
```

2024-10-09 01:31 UTC, m4xshen requested changes

2024-10-09 01:31 UTC, m4xshen commented on lua/hardtime/init.lua
> +               timer = vim.defer_fn(util.stopinsert, config.max_insert_idle_ms)
We should cancel the function if user exit before `max_insert_idle_ms`. Otherwise there is a bug, for example:

`i` `<ESC>` (wait 4 seconds) `i`

In this case, the second insert mode will exit after 1 second, which is because the `stopinsert` triggered by first insert is now executed.

2024-10-09 02:08 UTC, csessh commented on lua/hardtime/init.lua
> +               timer = vim.defer_fn(util.stopinsert, config.max_insert_idle_ms)
You are right. 
I've made some changes to ensure timer resets

2024-10-09 12:27 UTC, m4xshen approved these changes

2024-10-12 15:50 UTC, merged

2024-10-12 15:50 UTC, m4xshen commented
@csessh It is now merged. Thanks for your PR!