fix: mouse not working in terminal
m4xshen/hardtime.nvim pull request #120
Opened 2024-11-21 09:21 UTC by hankertrix

Also updated the deprecated function `nvim_buf_get_option` to `nvim_buf_get_option_value`.

Fixes #72

2024-12-17 05:28 UTC, hankertrix commented
Any feedback on this?

This fixes using the mouse to exit terminal mode and ensures the terminal window behaves normally.

Before this fix, it was impossible to view the full output generated by a command if it was very long.

2024-12-19 13:47 UTC, m4xshen commented
@hankertrix thanks for the PR, I just tried it out and an error happens:

```
E5108: Error executing lua: ...ocal/share/nvim/lazy/hardtime.nvim/lua/hardtime/init.lua:43: attempt to call field 'nvim_buf_get_option_value' (a nil value)     
stack traceback:                                                                                                                                                
        ...ocal/share/nvim/lazy/hardtime.nvim/lua/hardtime/init.lua:43: in function 'should_disable'                                                            
        ...ocal/share/nvim/lazy/hardtime.nvim/lua/hardtime/init.lua:49: in function <...ocal/share/nvim/lazy/hardtime.nvim/lua/hardtime/init.lua:48>
```

My version:

```
NVIM v0.10.2                                                                                                                                                    
Build type: Release                                                                                                                                             
LuaJIT 2.1.1732813678  
```

2024-12-19 18:09 UTC, hankertrix commented
Okay, I fixed the issue.

2024-12-20 01:00 UTC, m4xshen requested changes

2024-12-20 01:00 UTC, m4xshen commented on lua/hardtime/init.lua
> +            if config.disable_mouse then
We should ignore the `disable_mouse` here. When Hardtime is in terminal, it should be fully disabled, which means mouse is allowed. In this way it fixes #72.

2024-12-20 01:00 UTC, m4xshen commented on lua/hardtime/init.lua
> +      })
Instead of only handle the case for terminal. We should also handle it for other filetypes in `disabled_filetypes`.

2024-12-20 04:23 UTC, hankertrix commented
Okay I have updated the code.

2024-12-20 05:37 UTC, m4xshen commented on lua/hardtime/init.lua
> +      })
@hankertrix seems that this is not resolved yet

2024-12-20 07:29 UTC, hankertrix commented on lua/hardtime/init.lua
> +      })
Uhm, which part isn’t resolved yet?

The function now calls `should_disable`, which covers all the disabled file types.

It still needs to check whether disabling the mouse is wanted before it disables the mouse when leaving terminal mode. Otherwise people who have configured to not disable the mouse would have their mouse disabled.

2024-12-20 07:47 UTC, m4xshen commented on lua/hardtime/init.lua
> +      })
> Instead of only handle the case for terminal. We should also handle it for other filetypes in `disabled_filetypes`.

This one

2024-12-20 08:15 UTC, hankertrix commented
I believe this should be resolved with the call to `should_disable`, which includes the `disabled_filetypes`.Let me know if I’m missing something.On 20 Dec 2024, at 3:47 PM, Max Shen ***@***.***> wrote:﻿
@m4xshen commented on this pull request.



In lua/hardtime/init.lua:
> +
+      vim.api.nvim_create_autocmd("TermEnter", {
+         group = hardtime_group,
+         callback = function()
+            if config.disable_mouse then
+               vim.opt.mouse = "nvi"
+            end
+         end,
+      })
+
+      vim.api.nvim_create_autocmd("TermLeave", {
+         group = hardtime_group,
+         callback = function()
+            if
+               config.disable_mouse
+               and vim.api.nvim_get_option_value("buftype", { buf = 0 })
+                  ~= "terminal"
+            then
+               vim.opt.mouse = ""
+            end
+         end,
+      })


Instead of only handle the case for terminal. We should also handle it for other filetypes in disabled_filetypes.

This one

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-12-20 12:02 UTC, m4xshen commented
> I believe this should be resolved with the call to `should_disable`, which includes the `disabled_filetypes`. Let me know if I’m missing something.

Yeah, but `TermEnter` only occurs when the user enters insert mode in terminal. Therefore, `should_disable` is not called when the user enters a file type such as `help`.

2024-12-20 15:39 UTC, hankertrix commented
Ah okay, I get what you want now.

2024-12-20 16:21 UTC, hankertrix commented
I made the changes to the code so that the mouse is always enabled for disabled file types.

2024-12-22 02:58 UTC, merged

2024-12-22 02:58 UTC, m4xshen commented
Thanks a lot for the PR!

2024-12-22 03:18 UTC, hankertrix commented
You’re welcome!

Thanks for merging!